### PR TITLE
Xception encoder

### PR DESCRIPTION
**Pull request by chlxydl**
add Xception encoder

### CODE REVIEW

**Comment by qubvel** [comment]
Thanks for PR,
Encoder now looks different to support additional features:
1) Add EncoderMixin inheritance
2) Features starts from same resolution and goes in descending spatial resolution order
3) Encoder should be able to return variable length of features, so called depth.

You can look at another reference implementations to fix yours.

If you have any questions - please, ask!

**Comment by qubvel** [comment]
Hi @chlxydl, is it going to be updated?

**Comment by chlxydl** [comment]
> Hi @chlxydl, is it going to be updated?

I'll update the code in this week，much office work before.

**Comment by qubvel** [comment]
in #102

**Pull request closed without merging**
