### PR TITLE
Adding Eca and Ceca channel attention modules

### PR DESCRIPTION
**Pull request by pfeatherstone**

### CODE REVIEW

**Comment by JulienMaille** [comment]
which papers are those attention modules coming from?

**Comment by pfeatherstone** [comment]
Those modules are pinched from timm (pytorch image models). I've found they work really well. The code inside timm references the papers.

**Comment by JulienMaille** [comment]
Do they increase your score specifically when your problems requires global information?

**Comment by pfeatherstone** [comment]
By using Eca I can reduce the number of channels and still get really good results. So I guess each channel carries unique information. Whereas without channel attention you can have a lot of duplicity. None of this is backed up theoretically. This is just based on what I've seen

**Pull request closed without merging**
