### PR TITLE
update diceloss

### PR DESCRIPTION
**Pull request by julienguegan**
In the master branch, DiceLoss is implemented in such a way that the loss computed is along all class masks while it should be a mean of each diceloss for each class. And so, multiclass segmentation does not work well. This update should correct this problem

### CODE REVIEW

**Comment by julienguegan** [comment]
So the idea is that previously in `f_score` the sum was done along all axis so if you had multiple class no distinction was done and so is one class was larger in the image and another class quite small the dice loss would still be low to take this imbalance issue, you have to compute a mean score along all class ...

**Comment by julienguegan** [comment]
also note that this was updated when using the version 0.1.2 ... I have seen that in the v.0.2.0 a new **Losses** repo have been created and a lot of updates have been done and that the file `utils/losses.py` will be deprecated in next version ... My modification in utils/losses.py might not be compatible with the current `losses/dice.py`

**Comment by Quallle** [comment]
Thanks a lot! Could you add ignore_index to JaccardLoss as well? Would be very much appreciated!

**Comment by julienguegan** [comment]
Hello @qubvel ! I would like to have your opinion on this matter, I don't know exactly all updates that have been done in the last version (0.2.0), does the news losses functions correct this issue ?

**Pull request closed without merging**
