### PR TITLE
Code Quality improvements

### PR DESCRIPTION
**Pull request by vfdev-5**
Hi @qubvel 

some minor code cosmetics:
- Fixed flake8 and code style
- Updated deps, travis
  - in tests on Travis I disabled pretrained weights downloading for faster checking. 
  - this part can be setup on nightly if needed.

PS.: in deployment phase I would suggest you to put your pypi token into Travis secret variable. Otherwise, a tag on fork could push to the pypi...

In my fork I added refinenet decoder : https://github.com/vfdev-5/segmentation_models.pytorch/tree/refinenet
if you think it can be helpful here I can send another pr.

### CODE REVIEW

**Comment by qubvel** [comment]
Hi @vfdev-5 
Thanks a lot for your contribution, I am refactoring models right now to add additinal features such as auxillary classification output (optional) and ability to vary depth of the models, so could you later rebase or recreate this PR after updating master branch? 
I like your idea to remove weights loading from travis :+1: .. that's annoying.

P.S. Is it really possible to push tag from fork? :thinking: 
Key is unique for each repo and should not work for other repos.

**Comment by vfdev-5** [comment]
> so could you later rebase or recreate this PR after updating master branch?

No problems, tell me when you are done with the refactoring. And how does it impact your current structure of `Model` etc ? I added also light-weight refinenet with mobilenetv2 encoder, do I need to recode it after your refactoring ?

>  Is it really possible to push tag from fork?

well, maybe, you are right about private key should be associated with your repository and possibly encrypted key wont be decrypted in a fork.

**Comment by qubvel** [comment]
The structure of a model became different:
 - model now consist of `encoder` `decoder` `segmentation_head` and `classification_head` (optional aux output build on top of encoder)
 - all encoder returns list of features starting from same spatial resolution as input (e.g. if input image is 32x32 ouput features should be a list of `[(32x32),  (16x16), (8x8), (4x4), (2x2), (1x1)]` of length 6.
 - encoders now support `depth` argument and return list of featurers depend on that (last feature spatial resolution should be H/2^depth, W/2^depth -> `depth=3`, input resolution `32x32` -> encoder out features would be a list `[(32x32),  (16x16), (8x8), (4x4)]`). You can think about `depth` as  about number of downsampling operations in `encoder`.

All this modifications you can view now in `models-refactoring` branch.
If you have any suggestions for improvement of upcoming changes please let me know. 
If you have any questions or misunderstood something please let me know, I will try to help!

**Comment by vfdev-5** [comment]
@qubvel I looked quickly `models-refactoring` branch and seems good. Well, I'll try to port merge my code with it and then I could have some more comments on this.

Idea about `depth` argument seems good. Anyway, it would be difficult to provide a generic fully flexible encoder with hooks, but there can be cases where 6 outputs and depth parameter wont cover a segmentation model specification (e.g. Light-weight RefineNet).

**Pull request closed without merging**
