### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by ssakhavi**
`timm` version has changed to 0.2.1 two months ago. Is it possible it can change here as well?

### CODE REVIEW

**Comment by ssakhavi** [comment]
Wait... It's not only about updating the requirements. Let me fix and I'll send PR again,

**Comment by qubvel** [comment]
Hi!
Do you have any ideas why PR fails?

**Comment by ssakhavi** [comment]
@qubvel Sorry for the mistake. 

The tests pass now.

**Comment by ssakhavi** [comment]
Actually, I noticed it has been addressed here #225

**Comment by qubvel** [comment]
Thanks!

**Pull request merged**
