### PR TITLE
ConvNeXtV2 Encoder

### PR DESCRIPTION
**Pull request by lanesket**

### CODE REVIEW

**Comment by qubvel** [comment]
Hi @lanesket 

Thanks a lot for your contribution, could you please:
1. refactor the encoder to have stages (see other encoders as examples)
2. add pre-trained weights parameters
3. update docs and readme with new encoders information

Thanks

**Comment by lanesket** [comment]
@qubvel All done ✅

**Comment by javierztl** [comment]
The pretrained weights' key names dont match the encoder's, need to mannul modify.
The smp default depth is 5, the convnextv2s are 4.

**Comment by qubvel** [comment]
Is there a way to use ConvNext from the latest `timm` version [v0.8.10dev0](https://github.com/rwightman/pytorch-image-models/releases/tag/v0.8.10dev0)? I will wait for a stable release to update the version requirement here, but you could already use a new encoder by updating the `timm` manually to [v0.8.10dev0](https://github.com/rwightman/pytorch-image-models/releases/tag/v0.8.10dev0)

**Pull request closed without merging**
